### Upload file
POST http://localhost:8080/attach/upload
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwicGhvbmUiOiI5OTgxNDUwMDQiLCJleHAiOjE2ODEzNDY0NDgsImlhdCI6MTY4MTI2MDA0OH0.msiBoomdXelrROuTRmDZ6JNt0KpEl-HVV2sCjTPqwFCMfKoL_1TN0enUODMFiNwfmkCo4DweoX_lUvfM7-7G6w
Content-Type: multipart/form-data; boundary=WebAppBoundary


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test.jpg"

< E:\frame.png

### open
GET http://localhost:8080/attach/open/7c3a6440-c3d1-468f-bc4b-cc33b44631dd.png
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwicGhvbmUiOiI5OTgxNDUwMDQiLCJleHAiOjE2ODEzNDY0NDgsImlhdCI6MTY4MTI2MDA0OH0.msiBoomdXelrROuTRmDZ6JNt0KpEl-HVV2sCjTPqwFCMfKoL_1TN0enUODMFiNwfmkCo4DweoX_lUvfM7-7G6w

### download
GET http://localhost:8080/attach/download/7c3a6440-c3d1-468f-bc4b-cc33b44631dd
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwicGhvbmUiOiI5OTgxNDUwMDQiLCJleHAiOjE2ODEzNDY0NDgsImlhdCI6MTY4MTI2MDA0OH0.msiBoomdXelrROuTRmDZ6JNt0KpEl-HVV2sCjTPqwFCMfKoL_1TN0enUODMFiNwfmkCo4DweoX_lUvfM7-7G6w