### CREATE TYPE
POST http://localhost:8080/post/type/create
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzkxNDg5NzgsInBob25lIjoiOTk4MzM5NTYxNjA4Iiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE2NzkyMzUzNzgsImlzcyI6Ik15SGVhbHRoIHRlc3QgcG9ydGFsaSJ9.ZLnlWQxw3Dqx5h-GDObruiZZuTmU7U3GJeUX8LI7RctQHFzbLd_S1P6J7AjECNKl0YRlkquq1xT7EUHZ194uwA
Content-Type: application/json

{
  "name": "Cat",
  "type": "ANIMAL"
}

### GET ANIMAL TYPES
POST http://localhost:8080/post/type/get/animal
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzkxNjg4ODYsInBob25lIjoiOTk4MTQ1MDA4Iiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTY3OTI1NTI4NiwiaXNzIjoiTXlIZWFsdGggdGVzdCBwb3J0YWxpIn0.pMqktlheCVIg0VhfJnRfhPfCGWX-ht5E6znQFKg5-eEnrH9gmHIW27MIs3RVlTC5Pd2-LPlAdVxAA3ZUvdzgSA

### GET PLANT TYPES
POST http://localhost:8080/post/type/get/plant
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzkxNjg4ODYsInBob25lIjoiOTk4MTQ1MDA4Iiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTY3OTI1NTI4NiwiaXNzIjoiTXlIZWFsdGggdGVzdCBwb3J0YWxpIn0.pMqktlheCVIg0VhfJnRfhPfCGWX-ht5E6znQFKg5-eEnrH9gmHIW27MIs3RVlTC5Pd2-LPlAdVxAA3ZUvdzgSA