### CREATE TYPE
POST http://localhost:8080/post/type/create
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzkxNDg5NzgsInBob25lIjoiOTk4MzM5NTYxNjA4Iiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE2NzkyMzUzNzgsImlzcyI6Ik15SGVhbHRoIHRlc3QgcG9ydGFsaSJ9.ZLnlWQxw3Dqx5h-GDObruiZZuTmU7U3GJeUX8LI7RctQHFzbLd_S1P6J7AjECNKl0YRlkquq1xT7EUHZ194uwA
Content-Type: application/json

{
  "name": "Cat",
  "type": "ANIMAL"
}

### GET ANIMAL TYPES
GET http://159.223.94.231:8080/category/get/plant
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwicGhvbmUiOiI5OTg5OTgxNDUwMDUiLCJleHAiOjE2ODMyMDc2OTYsImlhdCI6MTY4MzEyMTI5Nn0.6lJXABbNruCUr7ZzQiMV1o4pA0Hi2QJ7rzofLqh_8F3-4p6XeSI4OCN2obnySnejcmAg32yU54lzY24ChjxwPQ
### GET PLANT TYPES
GET http://159.223.94.231:8080/type/get/11
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwicGhvbmUiOiI5OTg5OTgxNDUwMDUiLCJleHAiOjE2ODMzMDI2MjYsImlhdCI6MTY4MzIxNjIyNn0.hppQ9KQWFNCVrw0oMXJTezh089fSkdIl5oafb5tO0gJpZBZv3U-Rn-ej_Db7W4UjbInED3S2l7wMtJdUy6-L1w