### edit full name
PUT localhost:8080/profile/full_name/Azimjon Nazarov
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzkxMzU3NjIsInBob25lIjoiOTk4MTQ1MDA4Iiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTY3OTIyMjE2MiwiaXNzIjoiTXlIZWFsdGggdGVzdCBwb3J0YWxpIn0.AOkGhK0Gjs82eGR3cWvV4E5cKTQIsspzvE-stOFXajQGNYDovL1sIc9FpYv9D4UI1mfeWS8tR7N6wBZKwejL4g

### edit email
PUT localhost:8080/profile/email/nazarovazimjon@gmail.com
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzkxMzU3NjIsInBob25lIjoiOTk4MTQ1MDA4Iiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTY3OTIyMjE2MiwiaXNzIjoiTXlIZWFsdGggdGVzdCBwb3J0YWxpIn0.AOkGhK0Gjs82eGR3cWvV4E5cKTQIsspzvE-stOFXajQGNYDovL1sIc9FpYv9D4UI1mfeWS8tR7N6wBZKwejL4g

### edit phone
PUT localhost:8080/profile/phone/998145007
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzkxMzU3NjIsInBob25lIjoiOTk4MTQ1MDA4Iiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTY3OTIyMjE2MiwiaXNzIjoiTXlIZWFsdGggdGVzdCBwb3J0YWxpIn0.AOkGhK0Gjs82eGR3cWvV4E5cKTQIsspzvE-stOFXajQGNYDovL1sIc9FpYv9D4UI1mfeWS8tR7N6wBZKwejL4g

### edit photo
PUT localhost:8080/profile/photo/c1bf8aad-c83f-45d1-b480-d07a70c1c3fb
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2NzkxMzczODIsInBob25lIjoiOTk4MTQ1MDA3Iiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTY3OTIyMzc4MiwiaXNzIjoiTXlIZWFsdGggdGVzdCBwb3J0YWxpIn0.O4KQe2DauE8pfXYGMErT5cF3nryscnrCsgVVygy0tYr4UKFu9v9IUAPPHS4Nfkh7bTzT3ntyuzrZjoZM5aWGkw